version: "3.8"

services:
  nextjs:
    image: node:latest
    container_name: portfolio-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    networks:
      - shared-network

networks:
  shared-network:
    name: shared-network
    external: true